apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP  # This is the default type, you can omit this line
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql